#!/bin/bash

mostrar_error_salir() {
    echo "$1"
    echo "$1" >> "$HOME/CopiaSeguridad/errores.txt" 
    exit 1
}

if [ "$#" -ne 0 ]; then
    mostrar_error_salir "Uso: $0"
fi

if ! command -v zenity &> /dev/null; then
    mostrar_error_salir "Error: Zenity no está instalado. Por favor, instálalo para usar esta aplicación."
fi

ruta_copia="$HOME/CopiaSeguridad"
if [ ! -d "$ruta_copia" ]; then
    mkdir -p "$ruta_copia"
fi

ruta=$(zenity --file-selection --directory --title="Selecciona el directorio" 2> /dev/null)
if [ $? -ne 0 ]; then
    mostrar_error_salir "No se ha seleccionado ninguna ruta."
fi

cp -r "$ruta" "$ruta_copia" >> "$HOME/CopiaSeguridad/salidas.txt" 2>> "$HOME/CopiaSeguridad/errores.txt"
if [ $? -ne 0 ]; then
    mostrar_error_salir "Error al realizar la copia de seguridad."
else
    zenity --info --text="Copia de seguridad realizada con éxito en $HOME/CopiaSeguridad." >> "$HOME/CopiaSeguridad/salidas.txt" 2>> "$HOME/CopiaSeguridad/errores.txt"
fi

exit
